org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true

GROUP=io.github.jevhee.literalshield
VERSION_NAME=0.1.0-SNAPSHOT
POM_URL=https://github.com/jevhee/literal-shield
POM_SCM_URL=https://github.com/jevhee/literal-shield
POM_SCM_CONNECTION=scm:git:https://github.com/jevhee/literal-shield.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/jevhee/literal-shield.git
POM_DEVELOPER_ID=jevhee
POM_DEVELOPER_NAME=Jevhee

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
